### ISSUE TITLE
Additional enhancements and small fixes

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-dcatapit#214]
After some testing we found the following to be fixed:

- [x] The Region RDF vocabulary is no longer available at the URL specified in README:
https://raw.githubusercontent.com/italia/daf-ontologie-vocabolari-controllati/master/VocabolariControllati/ClassificazioneTerritorio/Istat-Classificazione-08-Territorio.rdf

I used the following one:

https://github.com/italia/daf-ontologie-vocabolari-controllati/raw/c998fb435ee77082880b6f98e230ec5273a09e6d/VocabolariControllati/ClassificazioneTerritorio/Istat-Classificazione-08-Territorio.rdf

- [x] In dataset edit form 'theme' and 'frequency' fields are not indicated as mandatory (using the usual red *)

- [ ] ~~The Region facet is emptied when the language is changed~~

- [x] In the Organization dataset list page the Region Facet is empty even if we have some regions set for the organization

- [x] **resource_license** and **dcat_subtheme** Facets should be available even if the dcatapit_subcatalog_facets plugin is not enabled. The plugin should adds only  **source_catalog_title** and **organization_region** Facets.

- [x] If I set a Region to an organization I cannot see it in the search Facet without a solr reindex

- [x] It seems that the License name is not localized when changing language (see Resource read page)

**Comment by giorgialodi** [comment]
@tdipisa the Regions controlled vocabulary has been created just fot the use in the dcatapit extension. The right one is the following: https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/territorial-classifications/regions We alredy saw that with @etj some months ago. We did not change it since then

**Comment by tdipisa** [comment]
Thank you so much @giorgialodi, @cezio please use the URL below:
https://raw.githubusercontent.com/italia/daf-ontologie-vocabolari-controllati/master/VocabolariControllati/territorial-classifications/regions/regions.rdf

**Comment by giorgialodi** [comment]
@cezio please use only https://w3id.org/italia/onto/CLV/Region that is absolutely certain and in case you want to get the label (name) you should use https://w3id.org/italia/onto/l0/name that is associated to each https://w3id.org/italia/onto/CLV/Region object. Thank you!

**Comment by cezio** [comment]
From chat with Tobia: we can populate missing keys for index by using default value for license/region for languages that are not translated and are present in list returned from `ckan.lib.i18n.get_locales()`

**Comment by tdipisa** [comment]
@cezio I commented out the point 3, we have to use language values provided in the vocabulary.

**Comment by cezio** [comment]
> If I set a Region to an organization I cannot see it in the search Facet without a solr reindex

I don't think we can avoid that. This is because only datasets are indexed in solr, not organizations. This separation works fine if organization data and package data are separate entities. But we are referencing organization's data within dataset in this case, so datasets need to be reindexed after organization is changed, to use new data from it.

**Comment by cezio** [comment]
> In the Organization dataset list page the Region Facet is empty even if we have some regions set for the organization

This was caused by  indexing of multiple values. Organization's region field could be multivalued, but then it would be stored as `{val1,val2}` notation, and that value would be passed to multilang to search for one tag. So, returned value was empty. I've added splitting that into separate values. **Be sure that solr has dynamic field** `organization_region_*` **with multivalue flag set on**

**Comment by tdipisa** [comment]
@cezio 
For the two latest comments I think that we need at least to properly update the README file to inform admins

**Comment by cezio** [comment]
From chat with Tobia: we have new regions data, which uses numeric id (https://w3id.org/italia/onto/CLV/Region) as a key. https://w3id.org/italia/onto/l0/name elements provide translations, but only for IT locales. That makes regions unusable in other languages, because user will get list of numbers:

![image](https://user-images.githubusercontent.com/116021/43510870-3ff58832-9577-11e8-98e5-34736ff50370.png)

This works correctly in Italian:

![image](https://user-images.githubusercontent.com/116021/43510920-6648e484-9577-11e8-9a72-d7b544b2a78c.png)


Should I use name elements for other languages too?

**Comment by tdipisa** [comment]
@cezio we have to use languages availables in the Regions vocabulary without implementing custom logic for this. 
@giorgialodi can we have the Regions  vocabulary updated with EN, FR and DE translations?

**Comment by giorgialodi** [comment]
@tdipisa not sure we can. That vocabulary was created starting from official data published by ISTAT. If ISTAT includes the translations, then fair enough. Otherwise, it is better not to include translations that are not recognized as official from a national point of view. In any case, what's the problem with having the vocabulary only in Italian? In the case of PBZ they are not able to visualize the names in German?

**Comment by tdipisa** [comment]
Hello @giorgialodi, in the vocabulary we have only IT locales so at the moment we are unable to visualize DE transaltions for PBZ. Anyway that's not a problem now since we don't need to show the Region facet for PBZ, but if ISTAT provides multiple locales for regions would be better to use them in our vocabulary for completeness in the future.
