### ISSUE TITLE
Licence: resource

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#58]
At the moment DCATAP(IT) is using the license field related to the dataset.
DCATAPIT requires the license info to be bound to the resource.

Handle a new licence field in resource.
It shall have multilang support in harvesting and serialization.

**Comment by cezio** [comment]
> It shall have multilang support

What do you mean by that?

**Comment by tdipisa** [comment]
@cezio, currently localized fields (for dataset, resources, groups and organizations) are managed through our ckanext-multilang extension. If there are some localized texts for license we need to take into account this during harvesting and serialization in order to properly store localized values in the DB.

**Comment by cezio** [comment]
> currently localized fields (for dataset, resources, groups and organizations) are managed through our ckanext-multilang extension. If there are some localized texts for license we need to take into account this during harvesting and serialization in order to properly store localized values in the DB.

Ok. From what i see, there's only license name localized. we don't store license text, just a reference to license text (which is outside ckan). Should we keep localized names?

```<foaf:name xml:lang="it">Creative Commons Attribuzione-Non Commerciale 3.0 Unported (CC BY-NC 3.0)</foaf:name>
   ...
    <dcatapit:referenceDoc rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">http://creativecommons.org/licenses/by-nc/3.0/</dcatapit:referenceDoc>
```

Sometimes license from vocabulary is already localized:
```
  <rdf:Description rdf:about="http://dati.gov.it/onto/controlledvocabulary/License/A27_CCBY20IT">
    <skos:broader rdf:resource="http://dati.gov.it/onto/controlledvocabulary/License/A2_Attribution"/>
    <dcatapit:referenceDoc rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">http://creativecommons.org/licenses/by/2.0/it/</dcatapit:referenceDoc>
    <dct:type rdf:resource="http://dati.gov.it/onto/controlledvocabulary/License/A2_Attribution"/>
    <skos:notation>A.2.7</skos:notation>
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
    <skos:prefLabel xml:lang="en">Creative Commons Attribution 2.0 Italy (CC BY 2.0 IT)</skos:prefLabel>
    <skos:prefLabel xml:lang="it">Creative Commons Attribuzione 2.0 Italia (CC BY 2.0 IT)</skos:prefLabel>
    <skos:broaderTransitive rdf:resource="http://dati.gov.it/onto/controlledvocabulary/License/A_OpenLicense"/>
    <owl:versionInfo>2.0 Italia</owl:versionInfo>
    <rdf:type rdf:resource="http://purl.org/dc/terms/LicenseDocument"/>
    <foaf:name xml:lang="en">Creative Commons Attribution 2.0 Italy (CC BY 2.0 IT)</foaf:name>
    <dct:identifier>A.2.7</dct:identifier>
    <foaf:name xml:lang="it">Creative Commons Attribuzione 2.0 Italia (CC BY 2.0 IT)</foaf:name>
    <skos:inScheme rdf:resource="http://dati.gov.it/onto/controlledvocabulary/License"/>
```

**Comment by giorgialodi** [comment]
Indeed. When I created the vocabulary I included all the required properties that are necessary to describe a license according to DCAT-AP_IT. These are "name, identifier, version, type". Therefore, if PAs use this URI http://dati.gov.it/onto/controlledvocabulary/License/A27_CCBY20IT it is enough: inside that vocabulary, for that URI, I can find all the properties that are required to be compliant with DCAT-AP_IT.  It is Linked Data  :-) These properties are available only at the third level of the hierarchy of the licenses (the last one) because it makes sense to specify them only when the actual license is described.

**Comment by cezio** [comment]
I've added simple select with license names indented depending on their level. 

![image](https://user-images.githubusercontent.com/116021/32835517-ade40054-ca06-11e7-95be-83a58cc22606.png)


However, I have a bit of a problem testing saving this, because form validation cries about form fields that are not present (and look more like dataset's fields):

![image](https://user-images.githubusercontent.com/116021/32835549-c9c99a2c-ca06-11e7-9225-e2da17098aa7.png)
