### ISSUE TITLE
Improvement for conformsTo: cardinality, multilang

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#59]
Support 0..n cardinality and multilang.

**Comment by cezio** [comment]
there's already some support in code:

https://github.com/geosolutions-it/ckanext-dcatapit/blob/master/ckanext/dcatapit/dcat/profiles.py#L126-L135

there's also package schema field: https://github.com/geosolutions-it/ckanext-dcatapit/blob/master/ckanext/dcatapit/schema.py#L252-L259

I'm not sure how this can be multilang'ed, because standard says it's a reference to `rdfs:Resource`, nothing more.

**Comment by cezio** [comment]
Do we have any closed terms list for dct:Standard? Or is there any value validation that could be applied? 

In basic scenario, could conformsTo be similar in functionality to tags list?

**Comment by etj** [comment]
Spec for conformsTo:

In Dataset:
- 0..N conformsTo - dct:conformsTo (O)

Standard class:
- `dct:identifier` 1..1 [rdfs:Literal]
- `dct:title` 0..N [rdfs:Literal] - multilang
- `dct:description` 0..N [rdfs:Literal] - multilang
- `dcatapit:referenceDocumentation` 0..N [rdfs:Literal] --> URL of ref doc

Example for `dcatapit:Standard`:
```
</dcatapit:Dataset>
    ...
    <dct:conformsTo rdf:resource="http://dati.gov.it/resource/Standard/standard-org"/>
    ...
</dcatapit:Dataset>


<dcatapit:Standard rdf:about="http://dati.gov.it/resource/Standard/standard-org">  
    <rdf:type rdf:resource="&dct;Standard"/> 
    <dcatapit:referenceDocumentation rdf:datatype="&xsd;anyURI">https://www.w3.org/TR/vocab-org/</dcatapit:referenceDocumentation>
    <dcatapit:referenceDocumentation rdf:datatype="&xsd;anyURI">https://www.w3.org/ns/org.rdf</dcatapit:referenceDocumentation>
    <dct:title xml:lang="en">W3C Org organization ontology</dct:title>
    <dct:description xml:lang="en">The ontology of the organizations</dct:description> </dcatapit:Standard>
```

**Comment by cezio** [comment]
@etj thanks!

So, it looks like it will need complex field and probably richer way of de/serializing

**Comment by cezio** [comment]
>dct:identifier 1..1 [rdfs:Literal]
dct:title 0..N [rdfs:Literal] - multilang
dct:description 0..N [rdfs:Literal] - multilang
dcatapit:referenceDocumentation 0..N [rdfs:Literal] --> URL of ref doc

To implement this in full, this requires 4 fields in UI, with one, `referenceDocumentation`, that can be added several times for one fieldset.




From what i see in templates, i'd need to add separate macro to get more complex fieldset, as currently only two-element fieldset are supported with `couple` macro.

**Comment by cezio** [comment]
implementation notes: because conforms to is quite complex, I'll keep it as json in extra field. Structure will be kept as  list of entries, each entry with keys `identifier`, `title`, `description`, and `referenceDocumentation`. Additionally, resource name from rdf will be kept in `_ref` field.

```
    [ {'identifier': str,
       '_ref': str,
       'title': {lang: str},
       'description': {lang: str},
       'referenceDocumentation: [ str, str],
      },..
    ]
```

At the moment, there's basic edit form support in ui:

![image](https://user-images.githubusercontent.com/116021/33143715-064e4254-cfbb-11e7-85d0-168926e8ee2c.png)

and in dataset view:

![image](https://user-images.githubusercontent.com/116021/33143684-ee5c2094-cfba-11e7-9bd2-ccdeaa927f07.png)
