### ISSUE TITLE
Facets for controlled vocabulary

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#86]
Add a feact for each conntrolled vocabulary:
- [ ] themes
- [ ] licenses
- [ ] geographic coverage
- [ ] subthemes

**Comment by cezio** [comment]
Few notes:
 * licenses and subthemes are covered with dedicated models, they're not in tag/vocabulary infrastructure because they're saved with additional structure information
 * themes, licenses and subthemes are kept in json fields, so probably they should be extracted from dataset in .before_index() into separate fields.

**Comment by cezio** [comment]
for subthemes (and themes as well, since it's connected here), this should be merged in https://github.com/geosolutions-it/ckanext-dcatapit/issues/85 (pr: https://github.com/geosolutions-it/ckanext-dcatapit/pull/94)

**Comment by cezio** [comment]
regions are in #87 (pr: https://github.com/geosolutions-it/ckanext-dcatapit/pull/111), which is still in review.
